// demo/taro-demo/src/pages/navigation/index.tsx
import { Text, Button, View } from '@tarojs/components'
import Taro, { useDidShow } from '@tarojs/taro'
import { useState } from 'react'
import './index.css'

export default function Navigation() {
  const [visits, setVisits] = useState(0)
  const [status, setStatus] = useState('Ready to navigate')

  useDidShow(() => {
    setVisits((value) => value + 1)
  })

  const openDetail = () => {
    setStatus('Opening detail page')
    Taro.navigateTo({ url: '/pages/detail/index?source=navigation' })
  }

  return (
    <View className='container'>
      <Text className='title'>Navigation</Text>
      <Text className='hint'>Use the button to open a detail page, then return with the page navigation controls.</Text>
      <Button id='navigation-detail' type='primary' onClick={openDetail}>Open detail page</Button>
      <Text className='status'>Status: {status}</Text>
      <Text className='status'>Navigation page shows: {visits}</Text>
    </View>
  )
}

// demo/uni-app-demo/src/pages/navigation/index.vue
<template>
  <view class="container">
    <text class="title">Navigation</text>
    <text class="hint">Use the button to open a detail page, then return with the page navigation controls.</text>
    <button id="navigation-detail" @tap="onOpenDetail">Open detail page</button>
    <text class="status">Status: {{ status }}</text>
    <text class="status">Navigation page shows: {{ visits }}</text>
  </view>
</template>

<script setup lang="ts">
import { onShow } from "@dcloudio/uni-app";
import { ref } from "vue";

const visits = ref(0);
const status = ref("Ready to navigate");

onShow(() => {
  visits.value += 1;
});

function onOpenDetail() {
  status.value = "Opening detail page";
  uni.navigateTo({ url: "/pages/detail/index?source=navigation" });
}
</script>
