// demo/uni-app-demo/src/pages/lists/index.vue
<template>
  <view class="container">
    <text class="title">Lists</text>
    <text class="hint">Repeated buttons use stable keys and synthetic ids for selector testing.</text>
    <button id="list-add" @tap="onAdd">Add item</button>

    <view id="synthetic-list" class="list">
      <view
        v-for="(item, index) in items"
        :id="`list-item-${item.id}`"
        :key="item.id"
        class="list-item"
      >
        <text class="item-label">{{ item.label }}</text>
        <view class="item-actions">
          <button class="item-button" size="mini" :data-index="index" @tap="onSelect(index)">Select</button>
          <button class="item-button" size="mini" :data-index="index" @tap="onRemove(index)">Remove</button>
        </view>
      </view>
    </view>

    <text class="status">Status: {{ status }}</text>
    <text class="status">Selected id: {{ selectedId || "none" }}</text>
  </view>
</template>

<script setup lang="ts">
import { ref } from "vue";

type DemoItem = { id: string; label: string };

const items = ref<DemoItem[]>([
  { id: "item-1", label: "Synthetic item 1" },
  { id: "item-2", label: "Synthetic item 2" },
  { id: "item-3", label: "Synthetic item 3" },
]);
const selectedId = ref("");
const nextId = ref(4);
const status = ref("No item selected");

function onSelect(index: number) {
  const item = items.value[index];
  if (!item) return;
  selectedId.value = item.id;
  status.value = `Selected ${item.label}`;
}

function onRemove(index: number) {
  const item = items.value[index];
  if (!item) return;
  items.value.splice(index, 1);
  if (selectedId.value === item.id) selectedId.value = "";
  status.value = `Removed ${item.label}`;
}

function onAdd() {
  const id = `item-${nextId.value}`;
  const item = { id, label: `Synthetic item ${nextId.value}` };
  items.value.push(item);
  nextId.value += 1;
  status.value = `Added ${item.label}`;
}
</script>

// demo/taro-demo/src/pages/lists/index.tsx
import { useState } from 'react'
import { Button, Text, View } from '@tarojs/components'
import './index.css'

type ListItem = {
  id: string
  label: string
}

const initialItems: ListItem[] = [
  { id: 'item-1', label: 'Synthetic item 1' },
  { id: 'item-2', label: 'Synthetic item 2' },
  { id: 'item-3', label: 'Synthetic item 3' }
]

export default function Lists() {
  const [items, setItems] = useState(initialItems)
  const [selectedId, setSelectedId] = useState('')
  const [nextId, setNextId] = useState(4)
  const [status, setStatus] = useState('No item selected')

  const addItem = () => {
    const item = { id: `item-${nextId}`, label: `Synthetic item ${nextId}` }
    setItems(items.concat(item))
    setNextId(nextId + 1)
    setStatus(`Added ${item.label}`)
  }

  const selectItem = (item: ListItem) => {
    setSelectedId(item.id)
    setStatus(`Selected ${item.label}`)
  }

  const removeItem = (item: ListItem) => {
    setItems(items.filter((candidate) => candidate.id !== item.id))
    if (selectedId === item.id) setSelectedId('')
    setStatus(`Removed ${item.label}`)
  }

  return (
    <View className='container'>
      <Text className='title'>Lists</Text>
      <Text className='hint'>Repeated buttons use stable indexes and synthetic ids for selector testing.</Text>
      <Button id='list-add' type='primary' onClick={addItem}>Add item</Button>
      <View className='list' id='synthetic-list'>
        {items.map((item, index) => (
          <View className='list-item' id={`list-item-${item.id}`} key={item.id}>
            <Text className='item-label'>{item.label}</Text>
            <View className='item-actions'>
              <Button className='item-button' size='mini' data-index={index} onClick={() => selectItem(item)}>Select</Button>
              <Button className='item-button' size='mini' data-index={index} onClick={() => removeItem(item)}>Remove</Button>
            </View>
          </View>
        ))}
      </View>
      <Text className='status'>Status: {status}</Text>
      <Text className='status'>Selected id: {selectedId || 'none'}</Text>
    </View>
  )
}
