// demo/uni-app-demo/src/pages/detail/index.vue
<template>
  <view class="container">
    <text class="title">Synthetic Detail</text>
    <text class="hint">This target page is part of the public demo navigation journey.</text>
    <text class="status">Opened from: {{ source }}</text>
    <button id="detail-back" @tap="onBack">Back to navigation</button>
  </view>
</template>

<script setup lang="ts">
import { onLoad } from "@dcloudio/uni-app";
import { ref } from "vue";

const source = ref("unknown");

onLoad((options) => {
  source.value = options?.source || "direct";
});

function onBack() {
  uni.navigateBack();
}
</script>

// demo/taro-demo/src/pages/detail/index.tsx
import { Button, Text, View } from '@tarojs/components'
import Taro, { useLoad } from '@tarojs/taro'
import { useState } from 'react'
import './index.css'

export default function Detail() {
  const [source, setSource] = useState('unknown')

  useLoad((options) => {
    setSource(options?.source || 'direct')
  })

  return (
    <View className='container'>
      <Text className='title'>Synthetic Detail</Text>
      <Text className='hint'>This target page is part of the public demo navigation journey.</Text>
      <Text className='status'>Opened from: {source}</Text>
      <Button id='detail-back' type='primary' onClick={() => Taro.navigateBack()}>Back to navigation</Button>
    </View>
  )
}
